import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8');
const app=read('assets/app.js');
const pub=read('public/assets/app.js');
const css=read('assets/styles.css');
const migration=read('supabase/migrations/20260812120144_phase6_9_cde_production_hardening.sql');
assert.equal(app,pub,'CDE production app root/public drift');
assert.match(migration,/document_directory_query/,'single-call document directory RPC missing');
assert.match(migration,/context_read_only/,'Document 360 read-only capability missing');
assert.match(migration,/project_context_operational/,'archived context backend guard missing');
assert.match(app,/document_directory_query/,'CDE client must use the consolidated document directory');
assert.doesNotMatch(app,/Promise\.all\(state\.projects\.filter[\s\S]{0,300}document_picker_query/,'CDE must not fan out a picker RPC per project');
assert.match(app,/fileLoadEpoch/,'CDE load race guard missing');
assert.match(app,/fileSearchEpoch/,'CDE search race guard missing');
assert.match(app,/documentDetailEpoch/,'Document 360 race guard missing');
assert.match(app,/filesContextReadOnly/,'archived/read-only client guard missing');
assert.match(app,/1073741824/,'1 GB client upload validation missing');
assert.match(css,/\.cde-readonly-banner/,'read-only CDE presentation missing');
console.log('Optimum 6.9 CDE production hardening static checks passed.');
